{% set version = "0.2.14" %}

package:
  name: pyaudio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PyAudio/PyAudio-{{ version }}.tar.gz
  sha256: 78dfff3879b4994d1f4fc6485646a57755c6ee3c19647a491f790a0895bd2f87

build:
  number: 0
  skip: true  # [win or osx]
  script:
    - export PORTAUDIO_PATH=$PREFIX  # [not win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - portaudio  # [not win]
    - jack  # [linux]
  run:
    - python
    - setuptools
    - portaudio  # [not win]
    - jack  # [linux]

test:
  imports:
    - pyaudio
  commands:

about:
  home: http://people.csail.mit.edu/hubert/pyaudio/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PortAudio Python Bindings.

extra:
  recipe-maintainers:
    - chiranthsiddappa
    - ocefpaf
    - scopatz
