{% set version = "0.2.14" %}

package:
  name: pyaudio
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/P/PyAudio/PyAudio-{{ version }}.tar.gz
  sha256: 78dfff3879b4994d1f4fc6485646a57755c6ee3c19647a491f790a0895bd2f87

build:
  number: 3
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - portaudio
    - jack
  run:
    - python
    - setuptools
    - portaudio 
    - jack

test:
  imports:
    - pyaudio
  commands:

about:
  home: http://people.csail.mit.edu/hubert/pyaudio/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PortAudio Python Bindings.

extra:
  recipe-maintainers:
    - chiranthsiddappa
    - ocefpaf
    - scopatz
