package:
  name: pyaudio
  version: "0.2.14"

source:
  url: https://pypi.org/packages/source/P/PyAudio/PyAudio-0.2.4.tar.gz
  sha256: 78dfff3879b4994d1f4fc6485646a57755c6ee3c19647a491f790a0895bd2f87

build:
  script: python -m pip install . -vv
  number: 3

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - portaudio
    - jack
  run:
    - python
    - setuptools
    - portaudio
    - jack

tests:
  - python:
      imports:
      - pyaudio
      pip_check: true

about:
  homepage: http://people.csail.mit.edu/hubert/pyaudio/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PortAudio Python Bindings.

extra:
  recipe-maintainers:
    - chiranthsiddappa
    - ocefpaf
    - scopatz
