{% set version = "0.2.13" %}

package:
  name: pyaudio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PyAudio/PyAudio-{{ version }}.tar.gz
  sha256: 26bccc81e4243d1c0ff5487e6b481de6329fcd65c79365c267cef38f363a2b56

build:
  number: 0
  # py2k needs alsa-lib-devel
  skip: true  # [win or py2k or osx]
  script:
    - export PORTAUDIO_PATH=$PREFIX  # [not win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - portaudio  # [not win]
    - jack  # [linux]
  run:
    - python
    - setuptools
    - portaudio  # [not win]
    - jack  # [linux]

test:
  imports:
    - pyaudio
  commands:

about:
  home: http://people.csail.mit.edu/hubert/pyaudio/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PortAudio Python Bindings.

extra:
  recipe-maintainers:
    - chiranthsiddappa
    - ocefpaf
    - scopatz
