appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: DYnLS0CGlvX+roggNLijl19cn+oqlDGdjDnPZhWP28ILek/TGImtiY+sUivJ7+v6rArVsP7WKvzvlrMgMzzkbbVr24GR9Imo96DMbAn0abWpLD0rPZZcfIZwMYnfao201xa9wpiYpmwg2PdBrF/nw0RYAU/ikzVqBDJ1Ksn/QAlFPEkw5ZGV8DpirvyDondfDv55+WUIdR6Q2cf9EmRkRu52DclKIqXy3cXBjBW+oLTJpG4j79G4KOx6KWA60JDeKyOsGCZIT2LBPL306colRS5jB1U4uLu8SaYYxDCpP7GsIg3FVDFGCvnfOmmR7XEKaa6w9QG7pGnHJHvJEr9zW0ZtXHkXvHc8J5viqbNhTytWIz4rdtdlnKasl9fQywTqctioWP05dWrgDe6BcwGoP+uLeFm/sKqIIrkHflhajlKQlCbrb3WJ88n8/FGrOqR7yK/aLkem5ovj39q520TU5KCoM+RXT6PEsesPvFf/L9M6ajhlQ+ip6RnYutWlUKsS3hekhq3lMq0ZPU8vHqO1mvYpTGqCksb7RldrjfgwyZUrUXV3WqtviPvYX5ILLQuoiiC15SdjYnAjka9D7TsworxQpU7uOU9WxLCWYMwvmQP05A3YFZK6ZTfK7uJfk2SJT9kbtnmnuWiQ/2MyoAOIg7mMkRNspVteCQBOzrv6Okw=}
conda_forge_output_validation: true
